### ISSUE TITLE
Readme: Mentioning of IEC standards

### ISSUE THREAD

**Issue by BirgitBoss** [OpenManufacturingPlatform/sds-manufacturing-information-model#10]
To my knowledge the ontology is based on IEC 62264-1 . However, when reading the Readme I do not get this impressions. It would be great to add a section about the standards used as basis for deriving the ontology.

**Comment by felix-loesch** [comment]
You are completely right. We will add a sentence in the readme on the derivation from the IEC 62264-1 standard.
