### ISSUE TITLE
Inconsistency in the class definition of Ontologies

### ISSUE THREAD

**Issue by ashishp98** [OpenManufacturingPlatform/sds-manufacturing-information-model#8]
**Problem:**
Spotted some inconsistency in the class definition of the ontology, specifically with the `rdfs:subClassOf owl:Thing`  property.

**Reason:**
Some ontologies contain a `rdfs:subClassOf owl:Thing` triple in the class definition. Since not all ontologies show the same pattern, an inconsistency occurs.

**Solution:**
Since the `rdfs:subClassOf owl:Thing` declaration bares no specific advantage, the removal is proposed. 
All classes are owl classes. Therefore, the `owl:Thing` relationship may be inferred. 

For reference, the lines of code where the `owl:Thing` property is present are  linked below;

https://github.com/OpenManufacturingPlatform/sds-manufacturing-information-model/blob/6d5d62cc4da272069580b1cbdc40a5b85754014b/omp_i40_core_param.ttl#L102

https://github.com/OpenManufacturingPlatform/sds-manufacturing-information-model/blob/6d5d62cc4da272069580b1cbdc40a5b85754014b/omp_i40_core_param.ttl#L110

https://github.com/OpenManufacturingPlatform/sds-manufacturing-information-model/blob/6d5d62cc4da272069580b1cbdc40a5b85754014b/omp_i40_core_param.ttl#L118

**Comment by felix-loesch** [comment]
It has been fixed in the ontologies.
